language: cpp
compiler: clang
dist: trusty
addons:
  apt:
    packages: &base_packages
      - cmake3
      - ninja-build
matrix:
  include:
    - env: CLANG_VERSION=5.0
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - *base_packages
            - clang-5.0
            - libclang-5.0-dev
            - llvm-5.0-dev
    - env: CLANG_VERSION=6.0
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - *base_packages
            - clang-6.0
            - libclang-6.0-dev
            - llvm-6.0-dev
before_install:
  - sudo ci/fix-clang-packaging.sh
  - CC=clang-$CLANG_VERSION
  - CXX=clang++-$CLANG_VERSION
  - export CMAKE_PREFIX_PATH=/usr/lib/llvm-$CLANG_VERSION
before_script:
  - mkdir build
  - cd build
  - cmake -GNinja ..
script:
  - ninja
  - ninja check
